export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  TENANTS: '/tenants',
  TENANT_DETAIL: '/tenants/:uuid',
  PLANS: '/plans',
  PLAN_CREATE: '/plans/create',
  PLAN_EDIT: '/plans/:uuid/edit',
  SUBSCRIPTIONS: '/subscriptions',
  COUPONS: '/coupons',
  CAMPAIGNS: '/campaigns',
  ANALYTICS: '/analytics',
  SETTINGS: '/settings',
  SETTINGS_GENERAL: '/settings/general',
  SETTINGS_REGION: '/settings/region',
  SETTINGS_SYSTEM: '/settings/system',
  SETTINGS_PAYMENT: '/settings/payment',
  SETTINGS_ENVIRONMENT: '/settings/environment',
  USERS: '/users',
  ROLES: '/roles',
  PERMISSIONS: '/permissions',
  ASSETS: '/assets',
  CLASSES: '/classes',
  CLASS_VIEW: '/classes/:uuid',
  PROFILE: '/profile',
} as const;
